var should = require('should'),
    fs = require('fs'),
    os = require('os'),
    path = require('path'),
    checksum = require('checksum'),

    TestHelper = require('../../helpers/TestHelper'),
    Replicator2Translator = require('../../../printableTranslation/translators/Replicator2'),

    printerType = {id :"F2F4B9B6-1D54-4A16-883E-B0385F27380D"},

    inputTerseFile = path.join(__dirname, '../../data/printables/FDMPrintableRep2.mic'),
    comparableTerseFile = path.join(__dirname, '../../data/comparables/FDMComparableRep2.gcode'),
    comparableTerseNoCR = path.join(os.tmpdir(), 'FDMComparableRep2.gcode'),
    outputTerseFile = path.join(os.tmpdir(), 'FDMPrintableRep2.gcode'),

    inputVerboseFile = path.join(__dirname, '../../data/printables/FDMPrintableRep2Verbose.mic'),
    comparableVerboseFile = path.join(__dirname, '../../data/comparables/FDMComparableRep2Verbose.gcode'),
    comparableVerboseNoCR = path.join(os.tmpdir(), 'FDMComparableRep2Verbose.gcode'),
    outputVerboseFile = path.join(os.tmpdir(), 'FDMPrintableRep2Verbose.gcode');

function removeCarriage(inputFile, outputFile) {
    var data = fs.readFileSync(inputFile, 'utf8');
    var result = data.replace(/[\r]/g, '');
    fs.writeFileSync(path.join(outputFile), result, 'utf8');
}

describe('Replicator 2 Translator', function () {
    var config = {
        verbose : undefined,
        precision : undefined
    };
    config.verbose = false;
    config.precision = {
        x: 3,
        y: 3,
        z: 3,
        e: 5,
        f: 0,
        p: 0,
        s: 0
    };

    var translator = new Replicator2Translator(printerType, undefined, undefined, config);

    it('should verify that it has the proper printerType ID', function (done) {
        Replicator2Translator.canTranslate(printerType).should.equal(true);
        done();
    });

    it('should translate a valid terse FDM file', function (done) {

        var config = {
            verbose : undefined,
            precision : undefined
        };
        config.verbose = false;
        config.precision = {
            x: 3,
            y: 3,
            z: 3,
            e: 5,
            f: 0,
            p: 0,
            s: 0
        };

        var translator = new Replicator2Translator(printerType, undefined, undefined, config);

        translator.translate(inputTerseFile, outputTerseFile)
        .then(function () {
            removeCarriage(comparableTerseFile, comparableTerseNoCR);
        })
        .then(function () {
            checksum.file(outputTerseFile, function (err, sum) {
                checksum.file(comparableTerseNoCR, function (err2, sum2) {
                    sum.should.equal(sum2);
                    done();
                });
            });
        })
        .catch(function (err) {
            done(err);
        });
    });

    it('should translate a valid verbose FDM file', function (done) {

        var config = {
            verbose : undefined,
            precision : undefined
        };
        config.verbose = true;
        config.precision = {
            x: 3,
            y: 3,
            z: 3,
            e: 5,
            f: 0,
            p: 0,
            s: 0
        };

        var translator = new Replicator2Translator(printerType, undefined, undefined, config);

        //Faking a timestamp to match the gospel mic file
        translator.theFile = "; Generated by Spark Print Studio Date: 2015 07 13 Time: 11 35\n";

        translator.translate(inputVerboseFile, outputVerboseFile)
        .then(function () {
            removeCarriage(comparableVerboseFile, comparableVerboseNoCR);
        })
        .then(function () {
            checksum.file(outputVerboseFile, function (err, sum) {
                checksum.file(comparableVerboseNoCR, function (err2, sum2) {
                    sum.should.equal(sum2);
                    done();
                });
            });
        })
        .catch(function (err) {
            done(err);
        });
    });

});
