var should = require('should'),
    fs = require('fs'),
    os = require('os'),
    path = require('path'),
    checksum = require('checksum'),

    TestHelper = require('../../helpers/TestHelper'),
    UltimakerTranslator = require('../../../printableTranslation/translators/Ultimaker'),

    printerType = {id :"8D39294C-FA7A-40F4-AB79-19F506C64097"},

    inputTerseFile = path.join(__dirname, '../../data/printables/FDMPrintableUltimaker.mic'),
    comparableTerseFile = path.join(__dirname, '../../data/comparables/FDMComparableUltimaker.gcode'),
    comparableTerseNoCR = path.join(os.tmpdir(), 'FDMComparableUltimaker.gcode'),
    outputTerseFile = path.join(os.tmpdir(), 'FDMPrintableUltimaker.gcode'),

    inputVerboseFile = path.join(__dirname, '../../data/printables/FDMPrintableUltimakerVerbose.mic'),
    comparableVerboseFile = path.join(__dirname, '../../data/comparables/FDMComparableUltimakerVerbose.gcode'),
    comparableVerboseNoCR = path.join(os.tmpdir(), 'FDMComparableUltimakerVerbose.gcode'),
    outputVerboseFile = path.join(os.tmpdir(), 'FDMPrintableUltimakerVerbose.gcode');

function removeCarriage(inputFile, outputFile) {
    var data = fs.readFileSync(inputFile, 'utf8');
    var result = data.replace(/[\r]/g, '');
    fs.writeFileSync(path.join(outputFile), result, 'utf8');
}

describe('Ultimaker Translator', function () {


    it('should verify that it has the proper printerType ID', function (done) {
        UltimakerTranslator.canTranslate(printerType).should.equal(true);
        done();
    });

    it('should translate a valid terse FDM file', function (done) {

        var config = {
            verbose : undefined,
            precision : undefined
        };
        config.verbose = false;
        config.precision = {
            x: 3,
            y: 3,
            z: 3,
            e: 5,
            f: 0,
            p: 0,
            s: 0
        };

        var translator = new UltimakerTranslator(printerType, undefined, undefined, config);

        translator.translate(inputTerseFile, outputTerseFile)
        .then(function () {
            removeCarriage(comparableTerseFile, comparableTerseNoCR);
        })
        .then(function () {
            checksum.file(outputTerseFile, function (err, sum) {
                checksum.file(comparableTerseNoCR, function (err2, sum2) {
                    sum.should.equal(sum2);
                    done();
                });
            });
        })
        .catch(function (err) {
            done(err);
        });
    });

    it('should translate a valid verbose FDM file', function (done) {

        var config = {
            verbose : undefined,
            precision : undefined
        };
        config.verbose = true;
        config.precision = {
            x: 3,
            y: 3,
            z: 3,
            e: 5,
            f: 0,
            p: 0,
            s: 0
        };

        var translator = new UltimakerTranslator(printerType, undefined, undefined, config);

        //Faking a timestamp to match the gospel mic file
        translator.theFile = "; Generated by Spark Print Studio Date: 2015 07 13 Time: 11 35\n";

        translator.translate(inputVerboseFile, outputVerboseFile)
        .then(function () {
            removeCarriage(comparableVerboseFile, comparableVerboseNoCR);
        })
        .then(function () {
            checksum.file(outputVerboseFile, function (err, sum) {
                checksum.file(comparableVerboseNoCR, function (err2, sum2) {
                    sum.should.equal(sum2);
                    done();
                });
            });
        })
        .catch(function (err) {
            done(err);
        });
    });

});
